-- =============================================================================
-- WAS Database - Entity Relationship Diagram
-- =============================================================================
-- 
-- ┌─────────────────────────────────────────────────────────────────────────┐
-- │                         DATABASE OVERVIEW                               │
-- └─────────────────────────────────────────────────────────────────────────┘
--
--  ┌──────────────┐          ┌──────────────────┐          ┌──────────────┐
--  │   contacts   │          │     messages     │          │   session    │
--  ├──────────────┤          ├──────────────────┤          ├──────────────┤
--  │ phone (PK)   │◄─────────┤ sender           │          │ key (PK)     │
--  │ name         │          │ recipient        │          │ value        │
--  │ is_business  │          │ sender_name      │          └──────────────┘
--  │ last_seen    │          │ text             │
--  │ updated_at   │          │ is_group         │
--  └──────────────┘          │ status           │
--                            │ priority         │
--                            │ media_type       │
--                            │ media_path       │
--                            │ media_filename   │
--                            │ media_extension  │
--                            │ media_size       │
--                            │ media_duration   │◄─────┐
--                            │ quoted_message_id│──────┼──── Self-reference
--                            │ error            │      │     (reply threading)
--                            │ retry_count      │      │
--                            │ max_retries      │      │
--                            │ message_timestamp│──────┘
--                            │ created_at       │
--                            │ processed_at     │
--                            └──────────────────┘
--                                    │
--                                    │ Chat JID links to
--                                    ▼
--  ┌──────────────────┐      ┌──────────────────┐
--  │ chat_settings    │      │  conversations   │
--  ├──────────────────┤      ├──────────────────┤
--  │ chat_id (PK)     │◄─────┤ id (PK)          │
--  │ muted_until      │      │ phone            │
--  │ pinned           │      │ name             │
--  │ archived         │      │ last_message     │
--  │ updated_at       │      │ last_message_time│
--  └──────────────────┘      │ unread_count     │
--                            │ is_group         │
--                            │ is_muted         │
--                            │ is_pinned        │
--                            │ is_archived      │
--                            │ avatar_url       │
--                            │ cached_at        │
--                            └──────────────────┘
--
-- =============================================================================
-- MESSAGE DIRECTION MODEL
-- =============================================================================
--
--  ┌─────────────────────────────────────────────────────────────────────────┐
--  │                     OUTGOING MESSAGE (1:1)                              │
--  │  sender = 'me'     ───────────────►     recipient = 'contact_phone'     │
--  └─────────────────────────────────────────────────────────────────────────┘
--
--  ┌─────────────────────────────────────────────────────────────────────────┐
--  │                     INCOMING MESSAGE (1:1)                              │
--  │  sender = 'contact_phone'    ◄────────    recipient = 'me'              │
--  └─────────────────────────────────────────────────────────────────────────┘
--
--  ┌─────────────────────────────────────────────────────────────────────────┐
--  │                     GROUP MESSAGE (outgoing)                            │
--  │  sender = 'me'     ───────────────►     recipient = 'group_jid'         │
--  └─────────────────────────────────────────────────────────────────────────┘
--
--  ┌─────────────────────────────────────────────────────────────────────────┐
--  │                     GROUP MESSAGE (incoming)                            │
--  │  sender = 'member_phone'  ─────────►   recipient = 'group_jid'          │
--  └─────────────────────────────────────────────────────────────────────────┘
--
-- =============================================================================
-- MESSAGE STATUS FLOW
-- =============================================================================
--
--  OUTGOING:   pending ──► processing ──► sent ──► delivered ──► read
--                │                          │
--                └────────► failed ◄────────┘
--                          (retry_count++)
--
--  INCOMING:   received
--
-- =============================================================================
-- MEDIA TYPES
-- =============================================================================
--
--  ┌────────────┬──────────────────────────────────────┐
--  │ Type       │ Description                          │
--  ├────────────┼──────────────────────────────────────┤
--  │ none       │ Text-only message                    │
--  │ image      │ Photo/picture attachment             │
--  │ video      │ Video file attachment                │
--  │ document   │ PDF, TOML, etc.                      │
--  │ voice      │ Voice message/audio note             │
--  │ sticker    │ Sticker attachment                   │
--  └────────────┴──────────────────────────────────────┘
--
-- =============================================================================
-- QUEUE PRIORITY
-- =============================================================================
--
--  Higher priority values are processed first.
--  Default priority is 0.
--
--  Queue query order: priority DESC, created_at ASC
--  (highest priority first, then oldest first within same priority)
--
-- =============================================================================
